ClusterLabs/libqb

lib/ipc_socket.c

In qb_ipcs_us_connect 4 files are created and bound.
I dont' know how this works for QB_LINUX or QB_CYGWIN.
But for the other OS the files are created and must be unlinked.
I use the same logic to construct the file names and unlink the files.
qb_ipcc_us_connect calls this
...
res = qb_ipc_dgram_sock_connect(r->response, "response", "request",
r->max_msg_size, &c->request.u.us.sock);
and qb_ipc_dgram_sock_connect calls
..
set_sock_addr
and in set_sock_addr the files are created if not Linux or Cygwin.
...
#if defined(QB_LINUX) || defined(QB_CYGWIN)
snprintf(address->sun_path + 1, UNIX_PATH_MAX - 1, "%s", socket_name);
#else
snprintf(address->sun_path, sizeof(address->sun_path), "%s/%s", SOCKETDIR,
socket_name);
#endif
...

Fix: Unlink files bound to unix domain sockets

---

configure.ac

Using ./configure CC=clang, the following flags are detected
as supported:
checking whether clang supports "-Wgnu89-inline"... yes
checking whether clang supports "-Wno-strict-aliasing"... yes
Which results in a lot of warnings during make:
warning: unknown warning option '-Wunsigned-char' [-Wunknown-warning-option]
warning: unknown warning option '-Wgnu89-inline' [-Wunknown-warning-option]
Clang doesn't support these flags, but the compile check returns a
warning, not an error:
configure:16649: checking whether clang supports "-Wunsigned-char"
configure:16662: clang -E  -Wunsigned-char conftest.c
warning: unknown warning option '-Wunsigned-char' [-Wunknown-warning-option]
1 warning generated.
configure:16662: $? = 0
configure:16663: result: yes

Fix detection of warning flags for clang

---

lib/loop_poll_kqueue.c

Fixes the following warnings under clang:
loop_poll_kqueue.c:58:2: warning: incompatible integer to pointer conversion assigning to 'void *' from 'intptr_t' (aka 'long') [-Wint-conversion]
EV_SET(&ke, fd, filters, EV_ADD | EV_ENABLE, 0, 0, (intptr_t)pe);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/event.h:54:16: note: expanded from macro 'EV_SET'
(kevp)->udata = (f);                    \
^ ~~~

The udata member of the kevent struct is a void *

---

tests/check_ipc.c

Each ipc server in the check_ipc unit tests needs a unique name that won't overlap with other instances of the unit tests that could be running in parallel. For example, a machine building i686 and x86_64 packages at the exact same time will stomp on each other's IPC tests because the ipc servers will have the same name. One of the builds might pass, while the other build will fail because 'make check' had weird looking IPC failures.

ipc test improvements.

---

configure.ac
lib/ringbuffer.c
lib/unix.c

libqb fails to build on the hppa architecture, because the built-in
testcases fail as can be seen here:
http://buildd.debian-ports.org/status/fetch.php?pkg=libqb&arch=hppa&ver=0.17.0-2&stamp=1409458262
I did analyzed why they fail, and the reason is that on hppa we have
somewhat more complicated requirements (e.g. alignments) which needs to
be followed in order to mmap shared pages between processes. It's
different than what can be done compared to ia64 and sparc.
The attached patch fixes libqb on the hppa architecture and with it all
testcases finish successful.
By the way, I fixed a small typo in configure.ac too where arm platforms
prints "ia64"...
Forwarded-From: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760199
Signed-off-by: Christoph Berg <myon@debian.org>

Fix alignment issues on hppa

---

.gitignore
include/qb/qblog.h
lib/log.c
lib/log_format.c
lib/log_int.h
tests/check_log.c

Amended commits to address issues from review:
* Got rid of unused argument in unit test.
* Replaced exquisite one-liner taking advantage of C short-circuiting with four-line if block ;-)
* Reverted qb_perror() to original implementation and added documentation note about effect of extended information marker on it

Implement extended information logging (aka split logging)

---

lib/ipc_int.h

When both the corosync and pacemaker has PID larger or equal 10000
and when the file descriptor is larger or equal 10 the desciption
will have at least 17 characters.
This fixes the issue reported here:
https://bugzilla.redhat.com/show_bug.cgi?id=1114852

Increase the length of description field.

---

.travis.yml
README.markdown
lib/Makefile.am
lib/ipcc.c
libqb.spec.in

This migrates the libtool soname versioning to use -version-info and throws in some minor other tweaks.

Fix: valgrind "invalid file descriptor" warning

---

lib/ipc_setup.c

In handle_new_connection(), connection_accept() could fail, which would
leave the state of the connection inactive. Previously, in this case,
the socket and the allocated qb_ipcs_connection would be leaked.
It can be produced with the following steps:
1) Run pacemaker_remoted without being connected by corosync nodes.
2) Run crm_mon on the same node.
3) The pacemaker_remoted ends up hitting the per-process fd limit.

Fix: ipc: Prevent fd and memory leaks in handle_new_connection()

---

lib/ipc_int.h
lib/ipc_setup.c
lib/ipc_socket.c

When creating a unix socket it's default gid is that of the parent
directory.  If the SOCKETDIR is owned by root:wheel with 1777 mode
some of the pacemaker daemons end up unable to communicate with one
another due to having insufficient permissions on the sockets.
This can be fixed by setting the client sockets gid to the primary
group of the server socket owner it's attempting to connect to.  And,
on the server side by setting the gid to the already captured gid
stored in the connection info.  This ensures that regardless of who
owns the socket directory, as long as the applications have r/w
access to it they should work.

ipc: set gid on unix sockets

---

configure.ac
lib/log.c

Grouped with pre-existing -Wsuggest-attribute=format treatment.

build: avoid too keen -Wmissing-format-attribute warning

---

tests/Makefile.am

The current master branch at https://github.com/ClusterLabs/libqb/commit/043cebb29e08aebd92cf09cea7cb6bc89d940b6e fails to build to `make rpm`.
I assume that the library is necessary only when `make check` and should not be packaged.
```
[root@build-centos71 libqb (master)]# git show --oneline
043cebb Merge pull request #190 from jnpkrn/build-syslog-tests-followup
[root@build-centos71 libqb (master)]# ./autogen.sh && ./configure && make rpm
(snip)
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/libqb-1.0rc3-1.3.043c.el7.x86_64
error: Installed (but unpackaged) file(s) found:
/usr/lib64/_syslog_override.so
/usr/lib64/_syslog_override.so.0
/usr/lib64/_syslog_override.so.0.0.0
RPM build errors:
Installed (but unpackaged) file(s) found: …
```

build: do not install syslog_override for the RPM packaging

---

.travis.yml

No need to waste time on redundant tests execution.

CI: "make check" already included in "make distcheck"

---

Makefile.am
docs/Makefile.am
include/Makefile.am
lib/Makefile.am
tests/Makefile.am

Generating the man pages definitely doesn't depend on existence of
(possibly generated) header files that we omit anyway.

build: fix out-of-tree build broken with 0b04ed5 (#184)

---

tests/Makefile.am
tests/check_array.c
tests/check_common.h
tests/check_ipc.c
tests/check_log.c
tests/check_loop.c
tests/check_map.c
tests/check_rb.c
tests/check_util.c

This reduces repeated code significantly, and allows for easier
supervision of what's being grouped to the suites + possibly what
timeouts apply.

tests: refactor test case defs using versatile add_tcase macro

---

Makefile.am
configure.ac
include/qb/qbconfig.h.in
tests/.gitignore
tests/Makefile.am
tests/print_ver.c

Mainly as a light-weight alternative to full-blown autoconf/pkg-config
machineries, whereby one can:
* workaround functionality not present in libqb up to 1.0 (inclusive)
- note that this versioning schema is being introduced *after*
1.0.0 release so one cannot tell that version from any older,
but will be able to safely identify any later one (1.0.1+)
and act accordingly
- example:
#if !defined(QB_VER_MAJOR) || ((QB_VER_MAJOR == 1) && (QB_VER_MINOR < 1))
#warning "Feature X not supported"
int do_foo(int arg) { };
#else
int
do_foo(int arg)
{
/* use feature X of libqb */
}
#endif
* make its program report libqb API version it was built with by
emitting QB_VER_STR symblic string (see tests/print_ver.c for example)
Also added is a print_ver test program to:
* emit how original unparsed …

API: introduce alternative, header-based versioning

---

build-aux/git-version-gen

Preserve, however, the modification by David Vossel to keep the script
working as expected also with lightweight tags (e.g., v1.0rc3).

build: use latest git-version-gen from gnulib (rev. 6118065)

---

configure.ac
include/qb/qbconfig.h.in
tests/print_ver.c

Under the influence of libxml2 and considering that actual "patch"
information in fact, if significant, ends up encoded in QB_VER_REST,
shift away from convention codified, e.g., by semver.org (not adored
by libqb, anyway) and rename designated PATCH component of the version
to MICRO accordingly.
Note that at this point, after a release without any header-based
versioning present and just a few commits after it was tentatively
introduced, it's a painless change.  Once this PATCH nomenclature
is leaked into a full release, there's no way to get rid of it
reasonably...

API: header-based versioning: s/PATCH/MICRO

---

include/qb/qbhdb.h

There are spelling error in include/qb/qbhdb.h, "failure" is
wroten as "faliure"

low:fixed:Spelling error of failure in qbhdb.h

---

lib/log_format.c

... where appropriate space is measured for, surprisingly, a char,
not for an int.  Note that's also the actual type used for both
de-/serializing, so there's no conflict.
Also bother to explain why, now surprisingly for real, an unsigned int
is scraped out from va_list (akin to to STDARG(3)).

Low: log: check for appropriate space when serializing a char

---

include/qb/qbdefs.h

If we want to see it again in the man page NAME section, where it can
be indexed by apropos or whatis.

docs: qbdefs.h: description must directly follow @file

---

configure.ac
lib/log_thread.c
lib/util.c

Again (see PR #187, which is superseded with this PR, if I am not mistaken), I am just a messenger.
Original available at [clusterlabs](http://oss.clusterlabs.org/pipermail/developers/2016-March/000164.html) (or [gmane](http://article.gmane.org/gmane.comp.clustering.clusterlabs.devel/125)).
```
* configure.ac: Define QB_GNU
* lib/log_thread.c: Replace second argument of
qb_log_thread_priority_set(): logt_sched_param.sched_priority by 0
when not supported by the OS.
* lib/util.c: Fall back to CLOCK_REALTIME in clock_getres() if
CLOCK_MONOTONIC fails.
```

Add Hurd support

---

lib/log_thread.c
tests/check_log.c

This fixes issue with would-fail-if-applied-to-thread-right-away
qb_log_thread_priority_set invocation when logging thread doesn't
exist yet, which will arrange for calling itself at the time of
thread's birth that is the moment it will actually fail.
In this + lock-could-not-have-been-initialized corner cases, the
already running thread would proceed as allowed by error condition
handling in the main thread, trying to dereference uninitialized
(or outdated) pointer to the lock at hand, resulting in segfault.
Also include the test that would have been caught that (we use the
fact that it doesn't matter whether setting of the scheduler parameters
fails due to bad input or just because of lack of privileges as it's
the failure at the right moment that is of our interest).
See also: …

Med: log_thread: logt_wthread_lock is vital for logging thread

---

configure.ac
examples/Makefile.am
include/qb/qbatomic.h
include/qb/qbloop.h
lib/Makefile.am
m4/ax_pthread.m4
m4/ax_restore_flags.m4
m4/ax_save_flags.m4
tests/Makefile.am

A couple of small things I noticed during packaging the 1.0.1 release. They don't make a big difference for a small project like libqb, but I decided to offer them for the sake of consistency and future-proofing. 
Especially for pthreads, where I switched to the standard macro from the Autoconf Archive.
I couldn't fully test this on systems where `gethostbyname` or the socket functions aren't in libc, so some corrections might be needed if you support them for real.
Please consider incorporating these patches.

Mostly Autoconf cleanups

---

configure.ac
docs/mainpage.h
lib/ipc_int.h
lib/ipc_setup.c
lib/ipc_socket.c
tests/check_ipc.c

This patch enables system-wide selection of filesystem or abstract sockets when running on Linux. The default is still to use abstract sockets.
Filesystem sockets are needed when running libqb servers inside some containers where the abstract socket name space is shared, so abstract socket names would clash.

Allow Linux to use filesystem sockets

---

configure.ac

Note also that gcc 5.4.0 and later default to the gnu11 version of the C11 standard.

Require c99 language support or newer

---

.gitignore
Makefile.am
autogen.sh

Various "configure" commits by wferi recently introduced new
compat/custom m4 macro files in m4 directory, which itself was,
so far, assumed ephemeral (not strictly needed for reproducing
the build successfully, i.e., bits that can be completely purged
when cutting down the project files to the bone).  Apparently,
this assumption no longer holds so several places need to be
adapted.
Amonst others, m4 directory no longer needs to be reinsured in
autogen.sh, and special care must be taken with .gitignore
and maintainer-clean-local target of the main Makefile.
See also PR #240.

build: follow-up on introducing custom m4 macros

---

configure.ac
lib/log_file.c

Using years-old benchmark attached to PostreSQL ML[1], I've observed
tiny bit more than double boost in speed when using fdatasync instead of
traditional fsync, on two Linux machines, each equipped with an SSD.
While the observation may be disputable (there are various
interpretations to what "synchronized I/O" actually means), by logical
extension of what the two are supposed to do, one can expect fdatasync
will perform no worse than fsync.  Having the timestamps correct is
really not a priority, compared to timely processing of the message
stream.  So let's use it whenever possible with QB_LOG_CONF_FILE_SYNC
requested.
[1] https://www.postgresql.org/message-id/1095055866.414539fadb90d@webmail.rawbw.com
https://www.postgresql.org/message-id/attachment/20659/syncbench.c

log: use fdatasync instead of fsync where possible

---

m4/ax_compat.m4

See also https://github.com/ClusterLabs/libqb/pull/240#issuecomment-267611985.
The build error occurs with RHEL 6 series,
```
[root@rhel69-1 libqb]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.9 (Santiago)
[root@rhel69-1 libqb]# autoconf --version
autoconf (GNU Autoconf) 2.63
[root@rhel69-1 libqb]# git log --oneline -n 1
333fc80 log: use fdatasync instead of fsync where possible (#263)
[root@rhel69-1 libqb]# ./autogen.sh
(snip)
autoreconf: running: /usr/bin/autoconf
configure:18155: error: possibly undefined macro: AS_VAR_COPY
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```
so I wrote this patch.
```
[root@rhel69-1 libqb]# vi m4/ax_compat.m4 …
```

configure: define AS_VAR_COPY

---

configure.ac

In cross-compilation, we can't run test programs, so configure just
bails out. Since there is no cache variable (e.g. ac_cv_blabla, we can't
even provide the correct result.
But in thise case, we don't really need to run to start with; we just
need to check if the toolchain headers know about CLOCK_MONOTONIC.
Signed-off-by: "Yann E. MORIN" <yann.morin.1998@free.fr>

bconfigure: fix CLOCK_MONOTONIC check for cross-compilation

---

libqb.spec.in

Beside the fact that libqb.pc is indeed arch-specific (see "libdir"
variable), it's also a matter of being disciplined per what distros
require:
https://fedoraproject.org/wiki/Packaging:Guidelines#Requiring_Base_Package
The syntactic provision at hand was introduced in rpm 4.6.0
(8+ years ago): http://rpm.org/user_doc/arch_dependencies.html
Signed-off-by: Jan Pokorný <jpokorny@redhat.com>

maint: make -devel package dependency on the main package arch-qualified

---

configure.ac
lib/Makefile.am

For the former, a prototype and the final code got (hm, mysteriously)
intertwisted.  For the latter, I am clearly guilty of (rare, anyway)
testing of the out-of-tree builds only with libqb-already-system-wide
scenario, which is rather shortsighted.
Thanks Fabio and his ci.kronosnet.org project for spotting that.

build: fix configure script neglecting, re-enable out-of-tree builds

---

Makefile.am
lib/Makefile.am
tests/Makefile.am
tests/check_ipc.c
tests/functional/GNUmakefile
tests/resources.test
tests/start.test

Miscellaneous fixes and cleanups to get 'make distcheck' to work on most platforms.
There's a thing in here to speed up the FreeBSD IPC stress tests. I know it means that the BSD test is no longer really a stress test, but it can take over an hour to run with 70000 iterations and that;s just getting in everyone's way.

Fix distcheck

---

include/qb/qbipcs.h
lib/ipc_int.h
lib/ipc_setup.c
lib/ipc_shm.c
tests/check_ipc.c

I've put in an extra check so that clients don't truncate the
SHM file if the server still exists. Sadly on FreeBSD we can't
get the server PID for the client (unless someone has a patch handy!)
so we still do the truncate when disconnected. As a backstop (and also
to cover the BSD issue) I've added a SIGBUS trap to the server shutdown
so that it doesn't cause a server crash.
Signed-off-by: Christine Caulfield <ccaulfie@redhat.com>

ipc_shm: Don't truncate SHM files of an active server

---

include/qb/qblog.h
lib/log.c
lib/log_blackbox.c
lib/log_file.c
lib/log_format.c
lib/log_int.h
lib/log_syslog.c
tests/check_log.c
tests/functional/log_test_client.err
tests/functional/log_test_interlib_client.err

Allow the logging line length to be changed. Any reasonable length is allowable, the default is 512 as before. Anything more than 512 incurs several mallocs.
Log lines that exceed the length will have ... as the last 3 characters.

Allow customisable log line length

---

configure.ac
m4/ax_check_link_flag.m4

some vendors default to RPATH, others to RUNPATH. The former does not allow override
with LD_LIBRARY_PATH when running binaries such as test suite and it was causing
problems on platforms where RPATH is default, by running the test suite against
the wrong library (out-of-tree vs in-tree).
This change has no effect on libqb itself, but only on the binaries.

tests: use RUNPATH instead of RPATH consistently

---

.gitattributes
.gitignore
Makefile.am
autogen.sh
configure.ac

This is meant as a lean, customized policy driven alternative
to the original proposal by Jan Friesse <jfriesse@redhat.com> that
balances the inherent trade-off in the opposite direction, so that the
configure.ac script is practically untouched and more weight and policy
is hardcoded in git-version-gen.  Problem with that approach stems from
(avoidable) effective fork of the respective gnulib's module and imposed
maintenance burden.
Speaking for libqb in particular, we should nonetheless make it
absolutely clear such in-development snapshots are nothing more,
nothing binding (not to think of viral injection of these bits
into circle of dependent packages upon their rebuilds), since the
changes accumulated since the last official release should only be
assumed firmly committed at the point …

build: allow for being consumed in a (discouraged) form of snapshots

---

include/qb/qblog.h
lib/log.c
lib/log_file.c
lib/log_int.h
lib/log_thread.c
tests/check_log.c

log: Add option to re-open a log file

---

configure.ac
lib/Makefile.am

We are building libqb in RHEL 6.
Although there was no problem up to v.1.0.1, since "AC_SEARCH_LIBS ([mq_open], [rt])" was deleted by the following modification, -lrt does not enter LIBS.
Therefore, in RHEL 6, HAVE_MONOTONIC_CLOCK is no longer defined from v 1.0.2.
https://github.com/ClusterLabs/libqb/commit/cb5ee921c04bfba24edf8b6f128d11161d161cec
Below is the information at v1.0.2 build time.
FYI: Since autogen.sh fails with the combination of v1.0.2 and RHEL6, we backport 9b50aa4.
```
[root@416fc3aee587 libqb]# git clean -d -x -f; git checkout v1.0.2 -f
HEAD is now at 608de6d... lib: update library version for upcoming 1.0.2 release
[root@416fc3aee587 libqb]# curl -OL https://github.com/ClusterLabs/libqb/commit/9b50aa4e5b84f495207b3f6185a1d6cb68af3f6d.patch && patch -d . -p1 < …
```

configure: Fixed the problem that librt was explicitly needed in RHEL 6

---

configure.ac
include/qb/qblog.h
lib/Makefile.am
lib/libqb.pc.in
lib/log.c
lib/log_int.h
lib/log_syslog.c
tests/check_log.c

As most of this patch is in the config system I'm hoping some nice person will fix it up for me - it does (seem to ) work, but I suspect it's not optimal.
The actual code is trivial.

log: Add configure-time option to use systemd journal instead of syslog

---

configure.ac

move from AC_PREPROC_IFELSE (strongly discouraged) to AC_COMPILE_IFELSE
our detection system was very weak and recent versions of clang did
show that PREPROC_IFELFE (cpp) would enable warning options that
the compiler does not support (clang).
use a full compilation test to detect what works and what doesn't.
Also expand the warning list to include new / renamed clang options
of equivalents already enabled for older versions of clang and gcc.

[build] fix supported compiler warning detection

---

examples/simplelog.c
include/qb/qblog.h
lib/Makefile.am
lib/log.c
lib/log_blackbox.c
lib/log_file.c
lib/log_format.c
lib/log_int.h
lib/log_syslog.c
lib/log_thread.c
tests/check_log.c

This adds a new %T option to the logging format for millisecond resolution timestamps.
It breaks a little-used API call (custom logging) but as we're heading for a 2.0 release anyway (because of the callsite changes) I don't see this as a big problem.

Add the option of hi-res (millisecond) timestamps

---

.travis.yml
include/qb/qbipcs.h
include/qb/qbloop.h
lib/ipc_setup.c
tests/Makefile.am
tests/check_ipc.c

It turns out that while 7f56f58 allowed for less blocking (thus
throughput increasing) initial handling of connections from clients
within the abstract (out-of-libqb managed) event loop, it unfortunately
subscribes itself back to such polling mechanism for UNIX-socket-check
with a default priority, which can be lower than desired (via explicit
qb_ipcs_request_rate_limit() configuration) for particular channel
(amongst attention-competing siblings in the pool, the term here
refers to associated communication, that is, both server and
on-server abstraction for particular clients).
On top of that, it violates the natural assumption that once (single
threaded, which is imposed by libqb, at least between initial accept()
and after-said-UNIX-socket-check) server accepts the connection, it
shall …

IPC: server: avoid temporary channel priority loss, up to deadlock-worth

---

tests/check_ipc.c

Follow-up for #352.
This was missed in the review for other primary targets.

tests: ipc: fix the no-GLib conditionalizing

---

.travis.yml
include/qb/qbipcs.h
include/qb/qbloop.h
lib/ipc_setup.c
tests/Makefile.am
tests/check_ipc.c

[version_1] IPC: server temporary channel priority loss

---

lib/ipc_setup.c

Terminating NUL on FreeBSD is not part of the sun_path.
Add it to use sun_path as a parameter of unlink.
Signed-off-by: Jan Friesse <jfriesse@redhat.com>

ipc: Fix named socket unlink on FreeBSD

---

lib/ipc_socket.c

the /etc/libqb/force-filesystem-sockets option got broken for some
applications in the last security update.

ipc: fix force-filesystem-sockets

---

lib/loop_poll_kqueue.c
tests/check_ipc.c

Reduce the number of iterations from 70000 to 5000. For what it's testing (multiple connections) the extra large number doesn't tell us anything significant, and just adds to the load on the CI and build systems - especially BSD but also the slower Linux systems. This has been a collegiate decision after discussion on IRC.
The EV_EOF message has been removed from the FreeBSD kqueue code - there is no equivalent of this on the epoll side and, again, it just slowed things down.
There's also a user-after-free bugfix to test_ipc_disconnect_after_created(), which currently only affects BSD but in theory could trigger anywhere.

Improve speed of IPC tests

---

configure.ac

those options are stricly meant for runtime debugging purposes.
do NOT use in production.
check gcc man pages on how to use ASAN and UBSAN.

[build] add --with-sanitizers= option for sanitizer builds

---

lib/ipc_setup.c

Response structure was not initialized completely,
when mkdtemp/chown failed, server was not accepting connection yet or
connect failed for some reason.
This is not an issue, but valgrind reports this
as a problem so it is easy to miss real problem then.
Solution is to initialize response before it is used.
Signed-off-by: Jan Friesse <jfriesse@redhat.com>

ipc: Always initialize response struct

---

tests/check_ipc.c

On newer Fedora systems that can have 32 bit PIDs, these long test
names can get truncated in the libqb internal buffers and thus break the
tests, so I've shortened the names.

tests: Shorten deadlock test names

---

Makefile.am

only mingle with configure.ac if configure.ac-t exists

[build] fix configure.ac in release tarball

---

lib/Makefile.am
lib/ipc_shm.c

Backport #381 in case there is another 1.0.* release.

[version_1] Set correct ownership if qb_ipcs_connection_auth_set() has been used

---

lib/ipc_setup.c
lib/ipc_shm.c

- The temporary directory that is used since 6a4067c1d1764d93d255eccecfd8bf9f43cb0b4d needs to be accessible by the group as well. This has been fixed on the [version_1](https://github.com/ClusterLabs/libqb/tree/version_1) branch (and in version 1.0.5) by 65d6fb37a28f3b41f2e73c49214a4c9e3533f15a, but not on master. Cherry-pick this fix (as well as another related fix to make the patch apply cleanly) for master.
- When [`qb_ipcs_connection_auth_set`](https://github.com/ClusterLabs/libqb/blob/6a4067c1d1764d93d255eccecfd8bf9f43cb0b4d/lib/ipcs.c#L938-L946) is used, the ownership of the temporary directory that is initially set in [`handle_new_connection`](https://github.com/ClusterLabs/libqb/blob/7f891f0069623edc0b2212bf559e70fa56ba5c12/lib/ipc_setup.c#L663) must be updated as well, so do …

Set correct ownership if qb_ipcs_connection_auth_set() has been used

---

include/qb/qblist.h

list: #include <stddef.h> in qblist.h

---

configure.ac
include/qb/qblist.h

This allows pointer arithmetics without issuing warning.
Signed-off-by: Jan Friesse <jfriesse@redhat.com>

qblist: Retype ptr in qb_list_entry to char*

---

lib/trie.c
tests/check_map.c

Trie fails on systems with unsigned chars when using characters over
126.
This needs looking over and running through the CI systems - hence the PR

trie: Don't assume that chars are unsigned < 126

---

include/qb/qblist.h

gcc10 has some additional pointer sanity checks, so we need to use a different system for getting offsets.

Backported fixes to allow applications to compile using gcc10

---

lib/log_dcs.c
lib/log_thread.c

It seems we can't avoiding locking in qb_log_dcs_get because
qb_array_get() isn't thread-safe.
Alternatives to this would be to add a - new - implementation of
the arrays or to stick the lock higher up (as in this patch).
We're logging here, so doing I/O, plus all the formatting
that goes on, I think the locking is a minimal intrusion on the CPU
relatively speaking.
This bug was seen in the test suite on BSD so it's not just theoretical
also wthread_should_exit was unprotected.

log: Fix threading races

---

tests/check_ipc.c

test: Add unit test for ipcs_connection_auth_set()

---

lib/array.c

helgrind threw out a couple more locking errors in the logging/array
code.

array: More locking fixes

---

doxygen2man/doxygen2man.c

Also tidy 'description' fields (get rid of superfluous newlines), fix a couple of crashes, and format RETURN VALUE sections more correctly.

doxygen2man - Print structure descriptions (where available)

---

doxygen2man/doxygen2man.c

make[2]: Entering directory '/builddir/build/BUILD/kronosnet-1.17/man'
gcc -DHAVE_CONFIG_H -I. -I..    -O3 -ggdb3 -Werror -Wall -Wextra -Wno-unused-parameter -pthread  -I/usr/include/libxml2   -c -o doxyxml-doxyxml.o `test -f 'doxyxml.c' || echo './'`doxyxml.c
doxyxml.c: In function 'allcaps':
doxyxml.c:414:13: error: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Werror=sign-compare]
414 |  for (i=0; i< strlen(name); i++) {
|             ^
cc1: all warnings being treated as errors
make[2]: *** [Makefile:623: doxyxml-doxyxml.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/kronosnet-1.17/man'
make[1]: *** [Makefile:567: all-recursive] Error 1

[doxy] fix build when more aggressive -W options are used

---

configure.ac
lib/unix.c

Using of posix_fallocate() guarantees that, if it succeed, the
attempting to write to allocated space range does not fail because of
lack of storage space. This prevents SIGBUS when trying to write to
mmaped file and no space left.
Co-Authored-by: Ivan Zakharyaschev <imz@altlinux.org>
Reported-by: Mikhail Kulagin <m.kulagin at postgrespro dot ru>

unix.c: use posix_fallocate()

---

tests/check_array.c
tests/check_ipc.c
tests/check_loop.c
tests/check_rb.c

fail_if() and fail_unless() macros are deprecated in more
recent versions of check and are buggy in 0.15, so replace
them with ck_assert() instead.

tests: Remove deprecated check macros

---

Makefile.am
build-aux/update-copyright.sh
configure.ac
docs/Makefile.am
doxygen2man/doxygen2man.1
doxygen2man/doxygen2man.c
include/qb/qbarray.h
include/qb/qbconfig.h.in
include/qb/qbdefs.h
include/qb/qbhdb.h
include/qb/qbipcc.h
include/qb/qbipcs.h
include/qb/qblist.h
include/qb/qbloop.h
include/qb/qbmap.h
include/qb/qbrb.h
include/qb/qbutil.h
m4/ax_prog_date.m4

This should help make builds reproducible.
I tried various methods of getting the date, using 'git' is no use as
it could be run from a tarball, using the file date doesn't work either
so this seems a reasonable compromise.

doxygen2man: Add option to read copyright line from the header file

---

doxygen2man/Makefile.am
doxygen2man/cstring.c
doxygen2man/cstring.h
doxygen2man/doxygen2man.c

Add support for @code blocks - this makes the libqb 'general' man pages look more complete now!
Because this made the resulting strings get HUGE, I eventually implemented a very simple string library to handle the mallocs so I'm not constantly mallocing huge areas or having huge amounts of data on the stack (bear in mind that get_codeline() is called recursively)

doxygen2man: Add support for @code blocks

---

doxygen2man/doxygen2man.c

It caused \f macros to get truncated and doesn't actually affect
the groffed output anyway

doxygen2man: Remove horrible hack

---

docs/.gitignore
docs/Makefile.am
docs/man.dox.in
doxygen2man/doxygen2man.1
include/qb/qbrb.h

The changes in `docs/man.dox.in` silenced some "file not found" warnings, but I didn't check the actual output (the resulting `qbipcc.h.3` has no real content with 2.0.1, but maybe I looked in the wrong way).
The removal of the `http` directory is entirely untested for now, but wanted to share the idea anyway.

doc related fixups

---

include/qb/qbipcc.h
lib/ipc_int.h
lib/ipc_setup.c
lib/ipcc.c
lib/unix.c
tests/check_ipc.c

We can't use SO_PEERCRED on the client fd when using socket IPC
becayse it's a DGRAM socket (pacemaker tries this). So provide
an API to get the server credentials that libqb has already
squirreled away for its own purposes.
Also, fix some unused-variable compiler warnings in unix.c
when building on systems withpout posix_fallocate().

ipc: add qb_ipcc_auth_get() API call

---

lib/ipcs.c

Fix from minhbq https://github.com/ClusterLabs/libqb/issues/422

ipcs: Add missing qb_list_del when freeing server

---

lib/ipcs.c

Hi All,
In the environment where libqb and Pacemaker are combined, in rare cases, a "Broken pipe" error occurs in new_event_notification () when stopped.
The phenomenon is reported and discussed in the following Pacemaker Bugzilla.
- https://bugs.clusterlabs.org/show_bug.cgi?id=5457
- https://bugs.clusterlabs.org/show_bug.cgi?id=5445 
This error can confuse the user.
Is it possible to lower the log level of libqb to debug?
In the future, if this error occurs, Pacemaker will consider changing to a log output that is a little easier to understand.
Best Regards,
Hideo Yamauchi.

ipcs : Decrease log level.

---

doxygen2man/doxygen2man.c

Brief descriptions are an important component of man pages, so I'm not sure this is wanted, but `qb_atomic_init`, `qb_hdb_base_convert`, `qb_hdb_nocheck_convert`, `qb_log_from_external_source_va`, `qb_log_real_va_`, `qb_loop_destroy` and `qb_util_stopwatch_split_ctl` currently lack one.

doxygen2man: ignore all-whitespace brief descriptions

---

doxygen2man/doxygen2man.c

if a line starts with a '.' (eg the '...' in qbarray.h) then
nroff thinks it's looking for a macro called '..'.
The easiest solution is to add a dummy format at the start of the line
(just adding \ seems not to work).
https://github.com/ClusterLabs/libqb/issues/428

doxygen2man: fix printing of lines starting with '.'

---

lib/strlcpy.c

https://github.com/ClusterLabs/libqb/issues/429

strlcpy: Check for maxlen underflow

---

lib/ipc_shm.c

This is an attempt to make sure that /dev/shm is cleaned up when a
server exits unexpectedly. Normally it's the server's responsibility
to tidy up sockets, but if it crashes or is killed with SIGKILL then
the client (us) makes a reasonable attempt to tidy up the server sockets
we have connected. The extra delay here just gives the server chance to
disappear fully. As a client we can get here pretty quickly but shutting
down a large server may take a little longer even when SIGKILLed.
The 1/100th of a second is an arbitrary delay (of course) but seems to
catch most servers in 2 tries or less.
See https://bugzilla.redhat.com/show_bug.cgi?id=1614166 for more info.
And yes, I'm expecting this to be controversial and anyone with better ideas is welcome.

ipcc: Have a few goes at tidying up after a dead server

---

include/tlist.h
lib/loop_timerlist.c
tests/check_loop.c

Fix several locking issues reported by helgrind

timers: Add some locking

---

tests/resources.test

resources.test has not checked the right filenames for a while.
Fix this, and also make sure we don't count (but do remove) the dlock
test files.

tests: Fix up resources.test

---

include/qb/qblog.h
lib/log.c
lib/log_dcs.c
lib/log_int.h
lib/log_syslog.c
tests/check_log.c

DON'T MERGE
The message-ids are used by systemd catalogs. (see https://github.com/ClusterLabs/sbd/pull/117)
To enable this feature the libqb should be configured with the
` --enable-systemd-journal` option.
IMPORTANT:
The libqb exposes the
```
struct qb_log_callsite
qb_log_callsite_get(...
qb_log_from_external_source_va(..
```
To make it completely backward compatible, they all three should come with
and without the `message_id` parameter. This would however require repeating a
good half of the libqb. We did only a half-measure: we provided the
`qb_log_from_external_source_va2`
to make it working with the corosync. It's not however backward compatible with the pacemaker.
@beekhof , @jfriesse , @jnpkrn , please give your feedback. (The PR done in the continuation of the conversation …

Add a message-id parameter for messages

---

tests/Makefile.am

When using slibtool (https://github.com/midipix-project/slibtool) instead of GNU libtool the build fails with undefined references to pthread.
```
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: bmcpt.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
This works with GNU libtool because it silently filters out `-no-undefined` while slibtool does not.
This can be easily fixed by added `$(PTHREAD_CFLAGS)` and `$(PTHREAD_LIBS)` where applicable.
Also see this downstream issue: https://bugs.gentoo.org/775605

build: Fix undefined pthread reference.

---

include/tlist.h
lib/loop_timerlist.c
tests/Makefile.am
tests/check_loop.c
tests/check_tlist.c

Previous timer was sorted list implementation of priority queue and very slow when number of timers increased. This is mostly not a problem because usually only few timers are used.  But for application where bigger number of timers are needed it may become problem.    
Solution is to use binary heap based priority queue which is much faster.
API is unchanged, just timerlist_destroy is added which should be called to free heap array. This function also destroys mutex (omitted when mutex was added).
It's worth noting that qb loop timer is using qb array which is (by default right now) limited to 65 536 entries and it is doing its own mapping of tlist entries and searching by simple for cycle (so lineary) so speed improvement here is really not big for real app.
I've used `check_tlist.c`to …

Implement heap based timer list

---

include/tlist.h
lib/loop_timerlist.c
lib/rpl_sem.c

pthread calls do not set errno, they return the error directly

Fix pthread returns

---

lib/loop_poll.c

qb_log calls malloc() and probably many other non-signal-safe
functions, so don't call it in the signal handler.
Thanks to Honza for spotting this
Signed-off-by: Christine Caulfield <ccaulfie@redhat.com>

poll: Don't log in a signal handler

---

include/qb/qbipcc.h
lib/ipc_int.h
lib/ipc_setup.c
lib/ipcc.c
tests/check_ipc.c

DO NOT pull yet, this is for review & CI only at this stage.

RFC:  ipcc: Add an async connect API

---

lib/ipcc.c

The errno value from qb_ipcc_connect was incorrectly negated
when I introduced qb_ipcc_async_connect()

ipcc: Fix errno returned from qb_ipcc_connect

---

lib/unix.c
tests/check_ipc.c

ZFS doesn't support posix_fallocate() so libqb IPC or RB would
always fail with EINVAL.
As there seems to be no prospect of a more useful return code,
trap it in a QB_BSD #ifdef. That way if we do have actual errors
in the posix_fallocate() call the Linux tests should still find them.
Also, stick a small sleep in the test_ipc_disconnect_after_created
test to allow the server to shutdown before killing it with SIGTERM
and causing a test failure. all the other uses of it seem to have this
sleep!

unix: Don't fail on FreeBSD running ZFS

---

tests/check_ipc.c
tests/resources.test

This isn't perfect, but it does tidy more of /dev/shm than
previously. Because some of the tests leave empty directories
we have no way of telling (in resources.test) whether they
belong to this test run, another test run, or a running
application.

test: Clean /dev/shm a bit better

---

lib/ringbuffer.c

covscan complained we don't check the blackbox header when
reading it in - quite reasonably
(first pass for covscan approval)

blackbox: Sanitize items read from the blackbox header

---

configure.ac
docs/Makefile.am
tests/Makefile.am
tests/ipc_sock.test
tests/libstat_wrapper.c
tests/resources.test
tests/start.test

(re-opening PR 380 that got lost in the Great Git Transition of 2021)
Provide an LD_PRELOAD library that simulates the presence
of /etc/libqb/use-filesystem-sockets so that we can test
that functionality without actually having the file on
the system and affecting everything else running on the
box.

tests: Run IPC with use-filesystem-sockets active

---

tests/ipc_sock.test
tests/resources.test

fix a couple of errors reported by covscan
1. /usr/lib64/libqb/tests/resources.test:8:34: warning[SC2039]: In POSIX sh, UID is undefined.
1. /usr/lib64/libqb/tests/resources.test:8:30: warning[SC2166]: Prefer [ p ] && [ q ] as [ p -a q ] is not well defined.
1. /usr/lib64/libqb/tests/ipc_sock.test:10:34: warning[SC2039]: In POSIX sh, UID is undefined.
1. /usr/lib64/libqb/tests/ipc_sock.test:10:30: warning[SC2166]: Prefer [ p ] && [ q ] as [ p -a q ] is not well defined.

tests: Make ipc test more portable

---

tests/check_ipc.c
tests/resources.test

This should, FINALLY, allow the libqb tests to run
and properly clean up up after themselves.

tests: clean up the last of the empty directories

---

tests/check_ipc.c

FreeBSD-devel can allocate more space than requested which causes
the check to fail. So check for >= allocated rather than ==

tests: Fix tests on FreeBSD-devel

---

configure.ac

... to make 2.71 happy. Also increase minimum version to 2.69 (10 years
old version so should be compatible enough).
There is still one warning left caused by AX_PTHREAD, but this is problem with AX_PTHREAD and fixed upstream (-> it will disappears itself one day)

configure: Modernize configure.ac a bit

---

lib/ipc_setup.c

ipc: Retry receiving credentials if the the message is short

---

lib/loop_timerlist.c
tests/check_loop.c

A timer in QB_POLL_ENTRY_JOBLIST doesn't necessarily have a t->timerlist_handle so that deref can segv. Also the comment assumes the timers are threaded - which as we have decided is definitely not true. So it's safe to move the check earlier.
In the tests, I've adjusted the timeouts so that they definitely happen at different times. On some architectures they can fire concurrently and in the wrong order.

timer: Move state check to before time check

---

tests/check_loop.c

Start the "check_time_left" timer before the "stop_job" timer so that we can be sure that it exists when "check_time_left" is run.

tests: Close race condition in check_loop

---

Makefile.am
configure.ac

Add `--disable-tests` to allow the user to disable tests. As a side-effect, this will avoid the following build failure when check is found:
```
libstat_wrapper.c:11:10: fatal error: gnu/lib-names.h: No such file or directory
11 | #include <gnu/lib-names.h>
|          ^~~~~~~~~~~~~~~~~
```
This build failure is raised since version 2.0.5 and https://github.com/ClusterLabs/libqb/commit/78df90b180740712d0c90b6d982b78241cc99d72
Fixes:
- http://autobuild.buildroot.org/results/450cfc36d4fd6dc71c138bec45f05b5a2d92a08d
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

Add --disable-tests option

---

lib/strlcpy.c

Otherwise GCC complains about ‘__builtin_strncpy’ specified bound
depends on the length of the source argument.
Signed-off-by: Ferenc Wágner <wferi@debian.org>

strlcpy: avoid compiler warning from strncpy

---

tests/libstat_wrapper.c

It doesn't appear to be needed.

test: Remove gnu/lib-names.h from libstat_wrapper.c

---

lib/log_blackbox.c
lib/unix.c

if the message was too long, then msg_len was added to the buffer size twice, thus causing potential data corruption (seen VERY rarely in the CI test - or, at least, I think it was this).
Also fix a double close() spotted by gcc13's -fanalyzer

blackbox: fix potential overlow/memory corruption

---

libqb.spec.in

Both Fedora and openSUSE now recommends to use SPDX shortname format for License.

spec: Migrate to SPDX license

---

tests/Makefile.am

Fix a ridiculous thinko in the test deps for -j

test - fix test dependancies

---

lib/log_blackbox.c
tests/check_log.c

qb_vsnprintf_serialize was called with 'max_size' as the limiting number for the length of the formatted log message. But the buffer also needs to contain the
log header (given by 'actual_size'), so we now pass 'max_size - actual_size' as the maximum length of the formatted log message.
Also added error checks to the blacbkbox calls at
the end of the test, as these now provide a proper test that the BB is functioning. Before they were
masking failures.

log: fix potential overflow with long log messages

---

lib/ringbuffer_helper.c

Why just this one?
There are LOADS of asserts in libqb, some are OK and some may be overkill. This one in particular is causing CI failures and so annoys me more than the rest.

Change assert in ringbuffer to a return code

---

doxygen2man/doxygen2man.c

This seems to be needed for newer versions of libxml but shouldn't break older ones (CI to confirm!)

doxygen2man: Include libxml/parser.h

---

lib/ipc_setup.c
lib/ipcc.c
lib/ringbuffer.c
lib/ringbuffer_helper.c

When trying to open an IPC connection, log at info level rather than warning or error, because the caller has better context to know whether it's a problem or not. Users get distracted by error logs that don't actually indicate a problem.
Also lower some spammy messages to trace level.

Make some logs less noisy

---

configure.ac

Clang 16 starts to explicitly fail on undeclared functions. Unfortunately, while darwin provides the implementation, it's not available in any header.
This can be hacked around by providing a custom signature in the config header. There may be a less terrible way to achieve it.

Add fdatasync declaration on darwin
