- .travis.yml
- configure.ac
- include/qb/qblog.h
- lib/log.c
- tests/Makefile.am
- tests/_syslog_override.c
- tests/_syslog_override.h
- tests/check_log.c
This is alternative to PR #176 I personally prefer.
> Changing syslog identifier + testing syslog, preferred edition

- configure.ac
- docs/Makefile.am
There was a breakage noticed in two parts that received an update recently.
This PR aims to fix these.
> Follow-up fixes

- .travis.yml
- libqb.spec.in
...so as to obtain a first glance diagnostics in all cases with possibly
remote build system preventing other means of investigation.
> tests: ensure verbose output on failure w/ more recent automake

- .tito.spec.tmpl
- .tito/custom.py
- .tito/tito.props
- docs/Makefile.am
- tests/Makefile.am
It's meant to be hooked into GitHub through webhooks.
> build: allow for git -> automatic COPR builds integration

- .travis.yml
- lib/ipc_socket.c
- tests/check_ipc.c
...by enhancing the in-place diagnostics.
> Continue with investigation of intermittent failures in Travis CI (#234)

- .travis.yml
- configure.ac
- examples/Makefile.am
- include/qb/qbatomic.h
- include/qb/qbloop.h
- lib/Makefile.am
- libqb.spec.in
- m4/ax_pthread.m4
- m4/ax_restore_flags.m4
- m4/ax_save_flags.m4
- tests/Makefile.am
- tests/check_log.c
(hopefully the message of the last commit makes any sense)
> PR #240 + addendum (drop syslog-tests opt-in switch)

- tests/check_ipc.c
The sockets are named using a random() suffix in at attempt to isolate
concurrent test.  However random() always returns the same random number
by design ... unless pre-seeded with some value being unique enough for
the particular execution.
Borrowing the most of the above message from original "srandom" fix by
Chrissie who also discovered this issue (nice!), I thought it would be
more viable if we encoded such "unique enough" variables directly to
IPC name being generated, not relying on pseudorandom generators in any
way.  Hence this other fix.
Signed-off-by: Jan Pokorný <jpokorny@redhat.com>
> test: Fix random number generation in IPC tests (alt. fix)

- lib/ipc_socket.c
> Memleak fixes

- lib/ipc_socket.c
Signed-off-by: Christine Caulfield <ccaulfie@redhat.com>
> ipc: fix compile warning on non-Linux platforms

- include/qb/qbipcs.h
Signed-off-by: Jan Pokorný <jpokorny@redhat.com>
> Fix typo: repeat{ivi -> ed}ly

- build-aux/release.mk
Sign the tarballs as well as the sha256 files.
Also add my key ID to the file to save me effort.
> sign tarballs

- build-aux/release.mk
In part a follow-up for PR #259.
> build: some cleanups to release.mk

- tests/functional/GNUmakefile
Signed-off-by: Jan Pokorný <jpokorny@redhat.com>
> maint: fix "make maintainer-clean" not working in tests/functional

- docs/man8/qb-blackbox.8
- include/qb/qbarray.h
- lib/ipc_int.h
- lib/ipc_setup.c
- lib/ipc_shm.c
- lib/ipc_socket.c
- lib/ipcs.c
The first part of this is actually PR #347, the last two commits are new.
> Check for directory name truncation and provide safe removal

- include/qb/qbarray.h
- lib/array.c
I find the parentheses too elaborate for a typo, but couldn't think of anything better.
The second commit is mostly a test of my understanding.
> Maximum length of qbarray (documentation)

- lib/array.c
- lib/log.c
- lib/ringbuffer.c
I noticed some trivial bugs. I haven't done any testing.
> Handle errno properly

- include/qb/qbipcc.h
- include/qb/qbipcs.h
- lib/log_blackbox.c
- lib/log_format.c
- tests/_syslog_override.c
> lib: Fix some minor warnings from newer compilers

- configure.ac
- include/qb/qblist.h
DO NOT PULL - this patch generates warnings, but I want to test
it in the CI before sorting out the detail.
> list: fix list handling for gcc10

- tests/Makefile.am
- tests/functional/GNUmakefile
Fix make distcheck errors in the CI.
> Fix error in CI tests that seems to have suddenly happened

- doxygen2man/doxygen2man.1
- doxygen2man/doxygen2man.c
Also don't print (null) if there is no @brief description
for a function.
This means we're getting nearer to using this for libqb
> doxygen2man - Lots of new features & fixes for parsing libqb manpages

- doxygen2man/doxygen2man.c
- include/qb/qblog.h
Fix doxygen2man to add a RETURN section even if the file has
no @return stanza.
Add support for @c tags
Quote the % signs in qb_log_format_add manpage
> man: Tidy man pages

- lib/unix.c
https://github.com/microsoft/WSL/issues/902
> ipcs: ftruncate is not support on WIN32

- tests/Makefile.am
- tests/ipc_sock.test
- tests/resources.test
...but don't run it unless we are root
> test: Include ipc_sock.test in the libqb-tests rpm

- doxygen2man/doxygen2man.c
Also, prevent truncation of parameter descriptions in the
body of the man page due to strtok() usage.
> doxygen2man: Fix function parameter alignment
